import type { HostelSummary } from "@/app/_components/public-hostel-types";

const ROOM_IMAGES = [
  "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
  "https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=800&q=80",
];

export type MockHostel = HostelSummary & { isNew?: boolean };

function image(index: number) {
  return ROOM_IMAGES[index % ROOM_IMAGES.length];
}

export const MOCK_HOSTELS: MockHostel[] = [
  {
    address: "Lalitpur, Lalitpur",
    area: "Lalitpur",
    city: "Lalitpur",
    description: "A well-maintained boys hostel close to the ring road with 24/7 security.",
    facilities: ["Wi-Fi", "Food Included", "Laundry"],
    foodScore: 4,
    id: "himalayan-stay-boys-hostel",
    image: image(0),
    name: "Himalayan Stay Boys Hostel",
    owner: "Verified hostel",
    price: 11000,
    rating: 4.6,
    reviews: 32,
    roomTypes: ["Single", "Shared"],
    slug: "himalayan-stay-boys-hostel",
    status: "published",
    type: "boys",
    vacancy: 3,
    verified: true,
  },
  {
    address: "Putalisadak, Kathmandu",
    area: "Putalisadak",
    city: "Kathmandu",
    description: "A safe, well-lit girls hostel near major colleges with in-house food service.",
    facilities: ["Wi-Fi", "Food Included", "CCTV"],
    foodScore: 4,
    id: "city-light-girls-hostel",
    image: image(1),
    name: "City Light Girls Hostel",
    owner: "Verified hostel",
    price: 12500,
    rating: 4.4,
    reviews: 21,
    roomTypes: ["Shared"],
    slug: "city-light-girls-hostel",
    status: "published",
    type: "girls",
    vacancy: 3,
    verified: true,
  },
  {
    address: "New Baneshwor, Kathmandu",
    area: "New Baneshwor",
    city: "Kathmandu",
    description: "Modern co-living spaces designed for working students and professionals.",
    facilities: ["Wi-Fi", "Study Room", "Hot Water"],
    foodScore: 3,
    id: "green-view-student-hostel",
    image: image(2),
    name: "Green View Student Hostel",
    owner: "Verified hostel",
    price: 14000,
    rating: 4.3,
    reviews: 18,
    roomTypes: ["Single", "Shared"],
    slug: "green-view-student-hostel",
    status: "published",
    type: "co-living",
    vacancy: 5,
    verified: true,
  },
  {
    address: "Dillibazar, Kathmandu",
    area: "Dillibazar",
    city: "Kathmandu",
    description: "Budget-friendly boys hostel with a strong community and study-friendly rooms.",
    facilities: ["Wi-Fi", "Food Included"],
    foodScore: 4,
    id: "prime-stay-boys-hostel",
    image: image(3),
    name: "Prime Stay Boys Hostel",
    owner: "Verified hostel",
    price: 10500,
    rating: 4.2,
    reviews: 16,
    roomTypes: ["Shared"],
    slug: "prime-stay-boys-hostel",
    status: "published",
    type: "boys",
    vacancy: 2,
    verified: true,
  },
  {
    address: "Kuleshwor, Kathmandu",
    area: "Kuleshwor",
    city: "Kathmandu",
    description: "Popular boys hostel with easy access to public transport and markets.",
    facilities: ["Wi-Fi", "Food Included", "Parking"],
    foodScore: 4,
    id: "sunrise-boys-hostel",
    image: image(0),
    name: "Sunrise Boys Hostel",
    owner: "Verified hostel",
    price: 9500,
    rating: 4.6,
    reviews: 28,
    roomTypes: ["Shared"],
    slug: "sunrise-boys-hostel",
    status: "published",
    type: "boys",
    vacancy: 4,
    verified: true,
  },
  {
    address: "Maitighar, Kathmandu",
    area: "Maitighar",
    city: "Kathmandu",
    description: "Quiet, secure girls hostel with attached bathrooms and hot water.",
    facilities: ["Wi-Fi", "Attached Bathroom", "Hot Water"],
    foodScore: 4,
    id: "peaceful-girls-hostel",
    image: image(1),
    name: "Peaceful Girls Hostel",
    owner: "Verified hostel",
    price: 13000,
    rating: 4.4,
    reviews: 24,
    roomTypes: ["Single", "Shared"],
    slug: "peaceful-girls-hostel",
    status: "published",
    type: "girls",
    vacancy: 3,
    verified: true,
  },
  {
    address: "Thamel, Kathmandu",
    area: "Thamel",
    city: "Kathmandu",
    description: "Central co-living hostel with a lively community and flexible room plans.",
    facilities: ["Wi-Fi", "Food Included", "Study Room"],
    foodScore: 3,
    id: "student-home-kathmandu",
    image: image(2),
    name: "Student Home Kathmandu",
    owner: "Verified hostel",
    price: 11500,
    rating: 4.3,
    reviews: 20,
    roomTypes: ["Shared"],
    slug: "student-home-kathmandu",
    status: "published",
    type: "co-living",
    vacancy: 5,
    verified: true,
  },
  {
    address: "Boudha, Kathmandu",
    area: "Boudha",
    city: "Kathmandu",
    description: "Comfortable stay near Boudhanath with reliable food and laundry service.",
    facilities: ["Wi-Fi", "Laundry"],
    foodScore: 3,
    id: "comfort-stay-hostel",
    image: image(3),
    name: "Comfort Stay Hostel",
    owner: "Verified hostel",
    price: 10000,
    rating: 4.2,
    reviews: 15,
    roomTypes: ["Shared"],
    slug: "comfort-stay-hostel",
    status: "published",
    type: "co-living",
    vacancy: 2,
    verified: true,
  },
  {
    address: "Lakeside, Pokhara",
    area: "Lakeside",
    city: "Pokhara",
    description: "Lakeside co-living hostel with scenic views and a relaxed atmosphere.",
    facilities: ["Wi-Fi", "Food Included"],
    foodScore: 4,
    id: "lakeside-view-hostel",
    image: image(0),
    name: "Lakeside View Hostel",
    owner: "Verified hostel",
    price: 9800,
    rating: 4.5,
    reviews: 19,
    roomTypes: ["Shared"],
    slug: "lakeside-view-hostel",
    status: "published",
    type: "co-living",
    vacancy: 4,
    verified: true,
  },
  {
    address: "Chipledhunga, Pokhara",
    area: "Chipledhunga",
    city: "Pokhara",
    description: "Friendly girls hostel close to campuses with reliable Wi-Fi and study rooms.",
    facilities: ["Wi-Fi", "Study Room"],
    foodScore: 3,
    id: "fewa-girls-hostel",
    image: image(1),
    name: "Fewa Girls Hostel",
    owner: "Verified hostel",
    price: 9200,
    rating: 4.3,
    reviews: 14,
    roomTypes: ["Shared"],
    slug: "fewa-girls-hostel",
    status: "published",
    type: "girls",
    vacancy: 3,
    verified: true,
  },
  {
    address: "Bagar, Pokhara",
    area: "Bagar",
    city: "Pokhara",
    description: "Affordable boys hostel with parking and 24/7 water supply.",
    facilities: ["Wi-Fi", "Parking", "Hot Water"],
    foodScore: 3,
    id: "mountain-boys-hostel",
    image: image(2),
    name: "Mountain Boys Hostel",
    owner: "Verified hostel",
    price: 8800,
    rating: 4.1,
    reviews: 11,
    roomTypes: ["Shared"],
    slug: "mountain-boys-hostel",
    status: "published",
    type: "boys",
    vacancy: 5,
    verified: true,
  },
  {
    address: "Rambazar, Pokhara",
    area: "Rambazar",
    city: "Pokhara",
    description: "Simple, comfortable co-living rooms a short walk from the lake.",
    facilities: ["Wi-Fi", "Food Included"],
    foodScore: 3,
    id: "pokhara-comfort-stay",
    image: image(3),
    name: "Pokhara Comfort Stay",
    owner: "Verified hostel",
    price: 9500,
    rating: 4,
    reviews: 9,
    roomTypes: ["Shared"],
    slug: "pokhara-comfort-stay",
    status: "published",
    type: "co-living",
    vacancy: 2,
    verified: true,
  },
  {
    address: "Mangal Bazar, Lalitpur",
    area: "Mangal Bazar",
    city: "Lalitpur",
    description: "Heritage-area co-living hostel with a quiet courtyard and study space.",
    facilities: ["Wi-Fi", "Study Room", "CCTV"],
    foodScore: 3,
    id: "patan-heritage-hostel",
    image: image(0),
    name: "Patan Heritage Hostel",
    owner: "Verified hostel",
    price: 10800,
    rating: 4.4,
    reviews: 17,
    roomTypes: ["Shared"],
    slug: "patan-heritage-hostel",
    status: "published",
    type: "co-living",
    vacancy: 3,
    verified: true,
  },
  {
    address: "Jawalakhel, Lalitpur",
    area: "Jawalakhel",
    city: "Lalitpur",
    description: "Well-supervised girls residency close to Jawalakhel with attached bathrooms.",
    facilities: ["Wi-Fi", "Attached Bathroom", "Food Included"],
    foodScore: 4,
    id: "lalitpur-girls-residency",
    image: image(1),
    name: "Lalitpur Girls Residency",
    owner: "Verified hostel",
    price: 11200,
    rating: 4.2,
    reviews: 13,
    roomTypes: ["Single", "Shared"],
    slug: "lalitpur-girls-residency",
    status: "published",
    type: "girls",
    vacancy: 4,
    verified: true,
  },
  {
    address: "Kupondole, Lalitpur",
    area: "Kupondole",
    city: "Lalitpur",
    description: "Budget boys hostel with easy access to Kupondole's cafes and offices.",
    facilities: ["Wi-Fi", "Laundry"],
    foodScore: 3,
    id: "kupondole-boys-hostel",
    image: image(2),
    name: "Kupondole Boys Hostel",
    owner: "Verified hostel",
    price: 9700,
    rating: 4.1,
    reviews: 10,
    roomTypes: ["Shared"],
    slug: "kupondole-boys-hostel",
    status: "published",
    type: "boys",
    vacancy: 2,
    verified: true,
  },
  {
    address: "Sanepa, Lalitpur",
    area: "Sanepa",
    city: "Lalitpur",
    description: "Spacious co-living hostel with generator backup and a dedicated study room.",
    facilities: ["Wi-Fi", "Generator", "Study Room"],
    foodScore: 4,
    id: "green-valley-co-living",
    image: image(3),
    name: "Green Valley Co-living",
    owner: "Verified hostel",
    price: 12000,
    rating: 4.3,
    reviews: 15,
    roomTypes: ["Shared"],
    slug: "green-valley-co-living",
    status: "published",
    type: "co-living",
    vacancy: 5,
    verified: true,
  },
  {
    address: "Bhaktapur Durbar, Bhaktapur",
    area: "Bhaktapur Durbar",
    city: "Bhaktapur",
    description: "Peaceful co-living hostel near the heritage square with home-style food.",
    facilities: ["Wi-Fi", "Food Included"],
    foodScore: 4,
    id: "durbar-square-hostel",
    image: image(0),
    name: "Durbar Square Hostel",
    owner: "Verified hostel",
    price: 8500,
    rating: 4,
    reviews: 8,
    roomTypes: ["Shared"],
    slug: "durbar-square-hostel",
    status: "published",
    type: "co-living",
    vacancy: 3,
    verified: true,
  },
  {
    address: "Suryabinayak, Bhaktapur",
    area: "Suryabinayak",
    city: "Bhaktapur",
    description: "Secure girls hostel with CCTV coverage and a dedicated warden.",
    facilities: ["Wi-Fi", "CCTV", "Hot Water"],
    foodScore: 3,
    id: "heritage-girls-hostel",
    image: image(1),
    name: "Heritage Girls Hostel",
    owner: "Verified hostel",
    price: 9000,
    rating: 4.1,
    reviews: 9,
    roomTypes: ["Shared"],
    slug: "heritage-girls-hostel",
    status: "published",
    type: "girls",
    vacancy: 4,
    verified: true,
  },
  {
    address: "Main Road, Biratnagar",
    area: "Main Road",
    city: "Biratnagar",
    description: "Reliable boys hostel for students attending nearby colleges.",
    facilities: ["Wi-Fi", "Parking"],
    foodScore: 3,
    id: "eastern-star-hostel",
    image: image(2),
    name: "Eastern Star Hostel",
    owner: "Verified hostel",
    price: 8000,
    rating: 3.9,
    reviews: 6,
    roomTypes: ["Shared"],
    slug: "eastern-star-hostel",
    status: "published",
    type: "boys",
    vacancy: 5,
    verified: true,
  },
  {
    address: "Traffic Chowk, Biratnagar",
    area: "Traffic Chowk",
    city: "Biratnagar",
    description: "Well-located girls hostel with home-cooked meals included.",
    facilities: ["Wi-Fi", "Food Included"],
    foodScore: 4,
    id: "koshi-girls-hostel",
    image: image(3),
    name: "Koshi Girls Hostel",
    owner: "Verified hostel",
    price: 8300,
    rating: 4,
    reviews: 7,
    roomTypes: ["Shared"],
    slug: "koshi-girls-hostel",
    status: "published",
    type: "girls",
    vacancy: 3,
    verified: true,
  },
  {
    address: "Kalimati, Kathmandu",
    area: "Kalimati",
    city: "Kathmandu",
    description: "No-frills, affordable boys hostel close to Kalimati market.",
    facilities: ["Wi-Fi"],
    foodScore: 2,
    id: "budget-stay-boys-hostel",
    image: image(0),
    name: "Budget Stay Boys Hostel",
    owner: "Verified hostel",
    price: 6200,
    rating: 3.8,
    reviews: 5,
    roomTypes: ["Shared"],
    slug: "budget-stay-boys-hostel",
    status: "published",
    type: "boys",
    vacancy: 3,
    verified: true,
  },
  {
    address: "Gwarko, Lalitpur",
    area: "Gwarko",
    city: "Lalitpur",
    description: "Low-cost co-living rooms for students on a tight budget.",
    facilities: ["Wi-Fi", "Food Included"],
    foodScore: 3,
    id: "student-corner-hostel",
    image: image(1),
    name: "Student Corner Hostel",
    owner: "Verified hostel",
    price: 6500,
    rating: 3.9,
    reviews: 6,
    roomTypes: ["Shared"],
    slug: "student-corner-hostel",
    status: "published",
    type: "co-living",
    vacancy: 4,
    verified: true,
  },
  {
    address: "Sinamangal, Kathmandu",
    area: "Sinamangal",
    city: "Kathmandu",
    description: "Budget girls hostel close to the airport with basic amenities.",
    facilities: ["Wi-Fi", "Laundry"],
    foodScore: 2,
    id: "value-stay-hostel",
    image: image(2),
    name: "Value Stay Hostel",
    owner: "Verified hostel",
    price: 7000,
    rating: 4,
    reviews: 6,
    roomTypes: ["Shared"],
    slug: "value-stay-hostel",
    status: "published",
    type: "girls",
    vacancy: 3,
    verified: true,
  },
  {
    address: "Balaju, Kathmandu",
    area: "Balaju",
    city: "Kathmandu",
    description: "Popular budget boys hostel with a strong community feel.",
    facilities: ["Wi-Fi", "Food Included"],
    foodScore: 3,
    id: "everest-youth-hostel",
    image: image(3),
    name: "Everest Youth Hostel",
    owner: "Verified hostel",
    price: 7500,
    rating: 4.1,
    reviews: 11,
    roomTypes: ["Shared"],
    slug: "everest-youth-hostel",
    status: "published",
    type: "boys",
    vacancy: 2,
    verified: true,
  },
  {
    address: "Balkumari, Lalitpur",
    area: "Balkumari",
    city: "Lalitpur",
    description: "Newly opened co-living hostel with modern furnishing and fast Wi-Fi.",
    facilities: ["Wi-Fi"],
    foodScore: 3,
    id: "modern-living-hostel",
    image: image(0),
    isNew: true,
    name: "Modern Living Hostel",
    owner: "Verified hostel",
    price: 12000,
    rating: 4,
    reviews: 2,
    roomTypes: ["Shared"],
    slug: "modern-living-hostel",
    status: "published",
    type: "co-living",
    vacancy: 4,
    verified: true,
  },
  {
    address: "Sanepa, Lalitpur",
    area: "Sanepa",
    city: "Lalitpur",
    description: "Newly listed girls hostel offering home-style food from day one.",
    facilities: ["Food Included"],
    foodScore: 4,
    id: "himalaya-girls-hostel",
    image: image(1),
    isNew: true,
    name: "Himalaya Girls Hostel",
    owner: "Verified hostel",
    price: 14000,
    rating: 4,
    reviews: 1,
    roomTypes: ["Single", "Shared"],
    slug: "himalaya-girls-hostel",
    status: "published",
    type: "girls",
    vacancy: 3,
    verified: true,
  },
  {
    address: "Chabahil, Kathmandu",
    area: "Chabahil",
    city: "Kathmandu",
    description: "Freshly listed co-living hostel built for students who study late.",
    facilities: ["Wi-Fi"],
    foodScore: 3,
    id: "the-study-hub-hostel",
    image: image(2),
    isNew: true,
    name: "The Study Hub Hostel",
    owner: "Verified hostel",
    price: 10500,
    rating: 4,
    reviews: 1,
    roomTypes: ["Shared"],
    slug: "the-study-hub-hostel",
    status: "published",
    type: "co-living",
    vacancy: 2,
    verified: true,
  },
  {
    address: "Pepsicola, Kathmandu",
    area: "Pepsicola",
    city: "Kathmandu",
    description: "New co-living hostel with home-cooked meals and a friendly community.",
    facilities: ["Food Included"],
    foodScore: 4,
    id: "young-minds-hostel",
    image: image(3),
    isNew: true,
    name: "Young Minds Hostel",
    owner: "Verified hostel",
    price: 11000,
    rating: 4,
    reviews: 1,
    roomTypes: ["Shared"],
    slug: "young-minds-hostel",
    status: "published",
    type: "co-living",
    vacancy: 2,
    verified: true,
  },
];

export const CITY_OPTIONS = ["Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur", "Biratnagar"];

export const HOSTEL_TYPE_STATS: Array<{
  type: MockHostel["type"];
  label: string;
  count: string;
  description: string;
}> = [
  {
    count: "125 hostels",
    description: "Safe, comfortable and affordable accommodation for boys.",
    label: "Boys Hostels",
    type: "boys",
  },
  {
    count: "98 hostels",
    description: "Secure and friendly spaces for female students.",
    label: "Girls Hostels",
    type: "girls",
  },
  {
    count: "64 hostels",
    description: "Modern co-living spaces to live, study and grow together.",
    label: "Co-living Spaces",
    type: "co-living",
  },
];

export const FACILITY_STATS: Array<{ label: string; count: number }> = [
  { count: 162, label: "WiFi" },
  { count: 128, label: "Food Included" },
  { count: 96, label: "Laundry" },
  { count: 72, label: "Parking" },
  { count: 104, label: "Attached Bathroom" },
  { count: 88, label: "Hot Water" },
  { count: 75, label: "Study Room" },
  { count: 110, label: "CCTV" },
  { count: 68, label: "Generator" },
];

export const TRUST_POINTS = [
  {
    description: "All hostels are verified for authenticity and quality.",
    title: "Verified Hostels",
  },
  {
    description: "No hidden charges. What you see is what you pay.",
    title: "Transparent Pricing",
  },
  {
    description: "24/7 support and safety-first approach for every student.",
    title: "Safe & Secure",
  },
  {
    description: "Real reviews from students like you to help you decide.",
    title: "Student Reviews",
  },
  {
    description: "Parents trust us for their child's safety and well-being.",
    title: "Trusted by Families",
  },
  {
    description: "Friendly support team ready to help you anytime.",
    title: "Dedicated Support",
  },
];
